### ISSUE TITLE
Port is no longer shut down properly

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/devtools#50]
When I ctrl+c mojo_run, I get an error like:
```
cannot bind 'tcp:5037'
ADB server didn't ACK
* failed to start daemon *
error: cannot connect to daemon
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "third_party/mojo_devtools/devtoolslib/android_shell.py", line 362, in stop_shell
    _MOJO_SHELL_PACKAGE_NAME]))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['third_party/android_tools/sdk/platform-tools/adb', 'shell', 'am', 'force-stop', 'org.chromium.mojo.shell']' returned non-zero exit status 255
error: device offline
error: device offline
```

Upon the next run, I get:
```
Failed to start http server for [('packages/', ['out/android_Debug/gen/dart-pkg/packages']), ('', ['.', 'out/android_Debug'])] on port 31839: Address already in use.
  Run `fuser 31839/tcp` to find out which process is using the port;
  or `fuser -k 31839/tcp` terminate it.
```

Killing the process and re-running gets me going one more time. This issue doesn't exist at 
9f7b02ae85ceec845d642c538411181787298049.

**Comment by ppiet** [comment]
I can't reproduce this error. What's your configuration? (host platform and adb_remote or direct device connection?)

**Comment by ppiet** [comment]
@tonygentilcore , does the issue still occur?

**Comment by tonygentilcore** [comment]
It was reproducing for me when running android target + linux host yesterday. It does not reproduce for me currently using the remote adb flow (mac remote + linux host + android target).

**Comment by ppiet** [comment]
I am back on android target + linux host and can't reproduce it. If you see this again, please reopen.
